#
# This file is part of Saft.
#
# (c) Konrad Abicht <hi@inspirito.de>
# (c) Natanael Arndt <arndt@informatik.uni-leipzig.de>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

coverage_clover: gen/coverage/clover.xml
json_path: gen/coverage/coveralls-upload.json
service_name: travis-ci
