#
# This file is part of Saft.
#
# (c) Konrad Abicht <hi@inspirito.de>
# (c) Natanael Arndt <arndt@informatik.uni-leipzig.de>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

language: php

dist: trusty

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - nightly

env:
    - VIRTUOSO=7.2.4.2

matrix:
    fast_finish: true
    include:
        - php: hhvm
    allow_failures:
        - php: nightly
        - php: hhvm

cache:
    directories:
        - $HOME/.composer/cache
        - virtuoso-opensource

sudo: true

before_install:
    - bash ./scripts/install-extensions.sh
    - bash ./scripts/install-virtuoso.sh
    - travis_retry composer install --dev --no-interaction
    # Install coveralls.phar
    - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    - chmod +x coveralls.phar
    - php coveralls.phar --version

script: vendor/bin/phpunit --coverage-clover gen/coverage/clover.xml

after_success:
  # Submit coverage report to Coveralls servers, see .coveralls.yml
  - travis_retry php coveralls.phar -v
