#
# This file is part of Saft.
#
# (c) Konrad Abicht <hi@inspirito.de>
# (c) Natanael Arndt <arndt@informatik.uni-leipzig.de>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

virtuosoConfig: &virtuosoConfig
    dsn: "VOS"
    username: "dba"
    password: "dba"
